# Site settings
title: Benjamin Rohaut
description: 'Neuro intensivist & scientist'
url: 'https://brohaut.github.io'
#baseurl: '/brohaut.github.io/'
#baseurl: ''
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Benjamin Rohaut'
  email: benjamin.rohaut@gmx.com
  
  #facebook_username: brohaut
  github_username:  brohaut
  linkedin_username:  Benjamin
  reddit_username: rohaut
  scholar_username: Benjamin
  twitter_username: Benrohaut
  researchgate_username: Benjamin
 
  
defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
